// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_vector_
NumericVector parse_vector_(CharacterVector x, char decimalMark, char groupingMark);
RcppExport SEXP _quantities_parse_vector_(SEXP xSEXP, SEXP decimalMarkSEXP, SEXP groupingMarkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< char >::type decimalMark(decimalMarkSEXP);
    Rcpp::traits::input_parameter< char >::type groupingMark(groupingMarkSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_vector_(x, decimalMark, groupingMark));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quantities_parse_vector_", (DL_FUNC) &_quantities_parse_vector_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_quantities(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
