on:
  workflow_dispatch:
  release:
    types: [published]

name: pkgdown

jobs:
  pkgdown:
    name: Build and deploy site
    uses: r-quantities/workflows/.github/workflows/pkgdown.yml@main
    secrets: inherit
